#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter nbextension enable --py --sys-prefix k3d
jupyter labextension install k3d
jupyter nbextension install --py --sys-prefix k3d